
-- 1.Show the percentage of wins of each bidder in the order of highest to lowest percentage.

SELECT IPL_BIDDER_DETAILS.BIDDER_ID,IPL_BIDDER_DETAILS.BIDDER_NAME,
(SELECT COUNT(BIDDER_ID) FROM IPL_BIDDING_DETAILS
WHERE IPL_BIDDING_DETAILS.bid_status='won' AND IPL_BIDDING_DETAILS.bidder_id= IPL_BIDDER_DETAILS.bidder_id )/
(SELECT NO_OF_BIDS FROM IPL_BIDDER_POINTS WHERE IPL_BIDDER_DETAILS.bidder_id=IPL_BIDDER_POINTS.bidder_id)*100 AS WIN_PERCENTAGE
FROM IPL_BIDDER_DETAILS ORDER BY WIN_PERCENTAGE DESC;
 
-- 2.Display the number of matches conducted at each stadium with stadium name, city from the database. 

SELECT IPL_STADIUM.STADIUM_ID,STADIUM_NAME,CITY, COUNT(IPL_MATCH_SCHEDULE.STADIUM_ID) AS TOTAL_MATCHES
FROM IPL_STADIUM
JOIN IPL_MATCH_SCHEDULE USING (STADIUM_ID) GROUP BY STADIUM_ID ORDER BY STADIUM_ID;
 
-- 3.In a given stadium, what is the percentage of wins by a team which has won the toss?

SELECT IPL_STADIUM.STADIUM_ID,STADIUM_NAME,CITY,
(SELECT COUNT(*) FROM IPL_MATCH JOIN IPL_MATCH_SCHEDULE ON IPL_MATCH_SCHEDULE.MATCH_ID=IPL_MATCH.MATCH_ID 
WHERE TOSS_WINNER=MATCH_WINNER AND IPL_MATCH_SCHEDULE.STADIUM_ID=IPL_STADIUM.STADIUM_ID)/
(SELECT COUNT(*) FROM IPL_MATCH_SCHEDULE WHERE IPL_MATCH_SCHEDULE.stadium_id = IPL_STADIUM.stadium_id)*100 AS WIN_PERCENTAGE
FROM IPL_STADIUM;


-- 4.Show the total bids along with bid team and team name.
SELECT BID_TEAM,IPL_TEAM.TEAM_NAME,COUNT(BID_TEAM) AS count_bid
FROM IPL_BIDDING_DETAILS 
JOIN IPL_TEAM 
ON IPL_TEAM.TEAM_ID=IPL_BIDDING_DETAILS.BID_TEAM
GROUP BY IPL_BIDDING_DETAILS.BID_TEAM
ORDER BY IPL_BIDDING_DETAILS.BID_TEAM ;

-- 5.Show the team id who won the match as per the win details.

# BELOW CODE ONLY DISPLAY TEAM ID OF MATCH WINNER 
SELECT MATCH_ID, IF(IPL_MATCH.MATCH_WINNER =1,IPL_MATCH.TEAM_ID1,IPL_MATCH.TEAM_ID2) AS WINNING_TEAM_ID  FROM IPL_MATCH;

# BELOW CODE ONLY DISPLAY TEAM ID AND TEAM NAME OF MATCH WINNER 
SELECT a.TEAM_ID AS WINNING_TEAM_ID ,b.TEAM_NAME,a.WIN_DETAILS FROM
(SELECT CASE WHEN MATCH_WINNER='1' THEN TEAM_ID1 WHEN MATCH_WINNER='2' THEN TEAM_ID2 END AS TEAM_ID,WIN_DETAILS FROM IPL_MATCH) a
LEFT JOIN (SELECT TEAM_ID,TEAM_NAME FROM IPL_TEAM) b ON a.TEAM_ID = b.TEAM_ID;


-- 6.Display total matches played, total matches won and total matches lost by team along with its team name.

SELECT IPL_TEAM_STANDINGS.TEAM_ID,IPL_TEAM.TEAM_NAME,SUM(IPL_TEAM_STANDINGS.MATCHES_WON) AS WON,
SUM(IPL_TEAM_STANDINGS.MATCHES_LOST) AS LOST, SUM(IPL_TEAM_STANDINGS.MATCHES_PLAYED) TOTAL_MATCH_PLAYED FROM IPL_TEAM_STANDINGS JOIN IPL_TEAM ON IPL_TEAM_STANDINGS.TEAM_ID=IPL_TEAM.TEAM_ID
GROUP BY  IPL_TEAM_STANDINGS.TEAM_ID; 


-- 7.Display the bowlers for Mumbai Indians team.

SELECT IPL_TEAM_PLAYERS.PLAYER_ID,IPL_PLAYER.PLAYER_NAME,IPL_TEAM_PLAYERS.PLAYER_ROLE,IPL_TEAM.TEAM_NAME
FROM IPL_TEAM_PLAYERS JOIN IPL_PLAYER ON IPL_TEAM_PLAYERS.PLAYER_ID=IPL_PLAYER.PLAYER_ID 
JOIN IPL_TEAM ON IPL_TEAM_PLAYERS.TEAM_ID=IPL_TEAM.TEAM_ID 
WHERE IPL_TEAM_PLAYERS.PLAYER_ROLE = 'BOWLER' AND IPL_TEAM.TEAM_NAME='Mumbai Indians';

-- 8.How many all-rounders are there in each team, Display the teams with more than 4 all-rounder in descending order.
SELECT IPL_TEAM.TEAM_NAME,COUNT(IPL_TEAM_PLAYERS.PLAYER_ROLE) AS COUNT
FROM IPL_TEAM_PLAYERS JOIN IPL_PLAYER ON IPL_TEAM_PLAYERS.PLAYER_ID=IPL_PLAYER.PLAYER_ID 
JOIN IPL_TEAM ON IPL_TEAM_PLAYERS.TEAM_ID=IPL_TEAM.TEAM_ID 
WHERE IPL_TEAM_PLAYERS.PLAYER_ROLE = 'ALL-ROUNDER' 
GROUP BY IPL_TEAM.TEAM_NAME
HAVING COUNT > 4 
ORDER BY COUNT DESC;